apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: techtrends
    spec:
      containers:
      - name: techtrends
        image: ashutoshmishraji/techtrends:latest
        
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          initialDelaySeconds: 15
          periodSeconds: 5
            

        readinessProbe:
          httpGet:
            path: /healthz
            port: 3111
            httpHeaders:
          initialDelaySeconds: 15
          periodSeconds: 5

        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
status: {}